---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app-container
        image: iboncas/app:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: production

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: LoadBalancer
  selector:
    app: app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all-traffic
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: app
  policyTypes:
  - Ingress
  - Egress
  ingress: []
  egress: []
  
---
#apiVersion: networking.k8s.io/v1
#kind: NetworkPolicy
#metadata:
#  name: allow-from-specific-ip
#  namespace: default  # Replace with your namespace if different
#spec:
#  podSelector:
#    matchLabels:
#      app: app  # Ensure this label matches your Deployment
#  policyTypes:
#  - Ingress
#  ingress:
#  - from:
#    - ipBlock:
#        cidr: YOUR_IP_ADDRESS/32
#    ports:
#    - protocol: TCP
#      port: 5000  # The port your Flask app listens on
